"""Initial migration

Revision ID: d43cfe2565fa
Revises: 
Create Date: 2020-11-27 16:30:20.180848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43cfe2565fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docket', sa.Column('arresting_officer', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'docket', 'officer', ['arresting_officer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docket', type_='foreignkey')
    op.drop_column('docket', 'arresting_officer')
    # ### end Alembic commands ###
